// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBil42pmR5Lp_v1JEs5bIgaXlfqPF1VZds',
    appId: '1:680254147213:web:5f93cf7e846fa3e6f9f0c4',
    messagingSenderId: '680254147213',
    projectId: 'ipoker-2334f',
    authDomain: 'ipoker-2334f.firebaseapp.com',
    storageBucket: 'ipoker-2334f.firebasestorage.app',
    measurementId: 'G-0QZJ1KPWGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVCRme5FtfYYuDfHTmLZLWAPNht5MNxM4',
    appId: '1:680254147213:android:f62f77e9e6aab777f9f0c4',
    messagingSenderId: '680254147213',
    projectId: 'ipoker-2334f',
    storageBucket: 'ipoker-2334f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJ8JIyPo3NiWTEER6Y_XuFyZhyVUMxv8',
    appId: '1:680254147213:ios:624665cce6d1f60ff9f0c4',
    messagingSenderId: '680254147213',
    projectId: 'ipoker-2334f',
    storageBucket: 'ipoker-2334f.firebasestorage.app',
    iosBundleId: 'com.example.planningPokerIfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoJ8JIyPo3NiWTEER6Y_XuFyZhyVUMxv8',
    appId: '1:680254147213:ios:624665cce6d1f60ff9f0c4',
    messagingSenderId: '680254147213',
    projectId: 'ipoker-2334f',
    storageBucket: 'ipoker-2334f.firebasestorage.app',
    iosBundleId: 'com.example.planningPokerIfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBil42pmR5Lp_v1JEs5bIgaXlfqPF1VZds',
    appId: '1:680254147213:web:a1b35f7333133a68f9f0c4',
    messagingSenderId: '680254147213',
    projectId: 'ipoker-2334f',
    authDomain: 'ipoker-2334f.firebaseapp.com',
    storageBucket: 'ipoker-2334f.firebasestorage.app',
    measurementId: 'G-KQ18TDBLJV',
  );
}
